#ifndef _ERR_HEADER_
#define _ERR_HEADER_

enum Err
{
	ACCEPTOR_CONSTRUCT_ERR	= -1,
	ACCEPTOR_NOT_FIND		= -2,
	LIBEVENT_NEW_BIND_ERR	= -3,
	SESSION_NOT_FIND		= -4,
	LIBEVENT_BUFFER_EVENT_CONSTRUCT_ERR = -5,
	CONNECTOR_CONSTRUCT_ERR = -6,
};

#endif
